### ISSUE TITLE
Cannot SSH to a running VM without using the --latest argument

### ISSUE THREAD

**Issue by iholder101** [containers/crun-vm#117]
Hello!

This issue is about running multiple VM instances and being able to SSH to all of them when needed.

### What I've tried
Installed crum-vm:
```shell
> dnf install crun-vm
```

Started a new VM (in the background):
```shell
> podman run --runtime crun-vm --name fedora -d quay.io/containerdisks/fedora:40
```

Trying to SSH into the machine:
```shell
> podman exec -it fedora1 -- --as fedora
Please login as the user "fedora" rather than the user "root".

> podman exec -it 752be31a16b7 -- --as fedora
Please login as the user "fedora" rather than the user "root".
```

The only way I can SSH is using the `--latest` argument:
```shell
> podman exec -it --latest -- --as fedora
Last login: Tue Aug 27 11:40:41 2024 from 10.88.0.1
[fedora@752be31a16b7 ~]$ 
```

### Actual behavior
Having to use `--latest` to SSH to the VM, which effectively means I can SSH only to a single VM (the latest one).

### Desired behavior
Can use container ID or name in order to SSH into every VM, not just the latest one.

### Test environment
```shell
> podman version
Client:       Podman Engine
Version:      4.9.4
API Version:  4.9.4
Go Version:   go1.21.8
Built:        Tue Mar 26 11:39:52 2024
OS/Arch:      linux/amd64
```

Running on Fedora 39.

/kind bug

**Comment by albertofaria** [comment]
Looks like the problem is that podman is not gobbling up the `--` since it comes after the container name, causing it to be interpreted as part of the command. I added some logic to have crun-vm drop an initial `--` in the command nonetheless to avoid confusion. Thanks for reporting this.
