### ISSUE TITLE
Can Ansible be executed against the VM?

### ISSUE THREAD

**Issue by ehelms** [containers/crun-vm#20]
When I saw this project, my first thought was can I replace our use of Vagrant in our project and centralize tooling for developers and CI on podman. For reference, our project that handles this is [forklift](https://github.com/theforeman/forklift) for the Foreman community.

Effectively we use Vagrant to spin up a VM, and then execute a bunch of Ansible against it. From the docs, I only saw examples of using `podman exec` to SSH to the VM. Is there a way to execute Ansible against the resulting VM?

**Comment by albertofaria** [comment]
I see that there are [Podman](https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_connection.html) and [Docker](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_connection.html) connection plugins for Ansible, which I assume would work fine with crun-vm.

Alternatively, note that you can also ssh into a VM using its container's external IP address, which you can retrieve using:

```console
$ sudo podman container inspect -f '{{.NetworkSettings.IPAddress}}' --latest
```

But this is rather cumbersome and doesn't work with rootless Podman.

**Comment by albertofaria** [comment]
Hi @ehelms, did you get a chance to try it out with connection plugins?
