### ISSUE TITLE
Consider supporting bootc bootable containers

### ISSUE THREAD

**Issue by albertofaria** [containers/crun-vm#26]
To run [bootc](https://github.com/containers/bootc/) bootable containers using crun-vm, users currently must first create a VM image from the container using something like [bootc-image-builder](https://github.com/osbuild/bootc-image-builder), and then pass that image to crun-vm.

We could potentially allow users to pass the bootc container directly to crun-vm, which would internally convert it into an image and run a VM from it. This would simplify the workflow for users.

bootc-image-builder requires root privileges, but we would want this to work with rootless podman. A possible solution is running it an ephemeral VM before launching the actual VM requested by the user.

**Comment by rhatdan** [comment]
Are you considering mounting the image via virtiofsd?

**Comment by albertofaria** [comment]
I was thinking of actually building the disk image and booting that. This would just save the user from having to do that themselves, with the added bonus of not requiring privileges.

**Comment by rhatdan** [comment]
If you can build the image without requiring privs?

**Comment by albertofaria** [comment]
crun-vm could internally run bootc-image-builder in a minimal VM prior to running the user's actual VM.
