### ISSUE TITLE
fails to start the vm with error /usr/bin/qemu-system-x86_64: No such file or directory

### ISSUE THREAD

**Issue by mrniranjan** [containers/crun-vm#9]
I have following versions:

podman-4.8.3-1
crun-1.12-1
crun-qemu manually compiled from the documentation provided
qemu-kvm-6.2.0-40

```
ls -l my-vm-image/
total 531844
drwxr-xr-x. 2 foobar foobar       18 Jan 11 10:44 etc
-rw-rw-r--. 1 foobar foobar 544604160 Jan 11 09:24 Fedora-Cloud-Base-39-1.5.x86_64.qcow2
```
when executing the podman 

```
$podman run --runtime crun-qemu -it --rm --rootfs my-vm-image "" 
Authorization not available. Check if polkit service is running or see debug message for more information.
error: Failed to define domain from /crun-qemu/domain.xml
error: Cannot check QEMU binary /usr/bin/qemu-system-x86_64: No such file or directory
```

I am executing the above command on a x86_64 system.

**Comment by mrniranjan** [comment]
The emulator that i have is "/usr/libexec/qemu-kvm" , is there an argument that i can use to pass the emulator or if it can autodetect , that would be great. Thanks

**Comment by rhatdan** [comment]
rpm -qf /usr/bin/qemu-system-x*
qemu-system-x86-core-8.1.3-1.fc39.x86_64

**Comment by mrniranjan** [comment]
I don't have that rpm on RHEL systems and i can create vm's using libvirt with /usr/libexec/qemu-kvm

**Comment by albertofaria** [comment]
@mrniranjan You can customize the emulator with [--merge-libvirt-xml](https://github.com/containers/crun-qemu/blob/main/docs/2-podman-docker.md#inspecting-and-customizing-the-libvirt-domain-xml), e.g. create an override.xml file:

```xml
<domain>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
  </devices>
</domain>
```

And apply it using --merge-libvirt-xml:

```console
$ podman run --runtime crun-qemu -it --rm --rootfs my-vm-image --merge-libvirt-xml override.xml
```

**Comment by xsgordon** [comment]
Maybe this is different in RHEL but on my Fedora system /usr/bin/qemu-kvm is the generic symlink that in turns links to whatever qemu-system-* is configured? Perhaps it is better to code to that than the more specific /usr/bin/qemu-system-x86_64 ?

**Comment by xsgordon** [comment]
@mrniranjan which RHEL version? I know how we handled qemu packaging changed a bit across 7/8/9.

**Comment by mrniranjan** [comment]
@xsgordon  Red Hat Enterprise Linux release 8.9 (Ootpa)

**Comment by albertofaria** [comment]
We now let libvirt choose the VM arch and emulator binary. @mrniranjan Please let me know if this fixes it for you.

**Comment by mrniranjan** [comment]
@albertofaria  --merge-libvirt-xml fixes the issue for me.

**Comment by mrniranjan** [comment]
@albertofaria will update you on that

**Comment by mrniranjan** [comment]
@albertofaria it works , thanks for the quick fix
